# Generated by Django 2.1 on 2018-08-10 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp_user_configs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconfigs',
            options={'verbose_name_plural': 'User Configs'},
        ),
        migrations.AlterField(
            model_name='userconfigs',
            name='brand_assets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cp_configs.BrandAsset'),
        ),
        migrations.AlterField(
            model_name='userconfigs',
            name='brand_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cp_configs.BrandIdentity'),
        ),
        migrations.AlterField(
            model_name='userconfigs',
            name='color_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cp_configs.ColorScheme'),
        ),
        migrations.AlterField(
            model_name='userconfigs',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.Member'),
        ),
        migrations.AlterField(
            model_name='userconfigs',
            name='templates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cp_configs.Template'),
        ),
    ]
