# Generated by Django 2.0.8 on 2018-09-28 11:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_member_activation_code'),
        ('cp_user_configs', '0002_auto_20180810_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.Member')),
            ],
        ),
        migrations.CreateModel(
            name='UserFormTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.Member')),
            ],
        ),
        migrations.AlterField(
            model_name='userconfigs',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.Member'),
        ),
    ]
