# Generated by Django 2.0.8 on 2018-10-11 08:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp_user_configs', '0003_auto_20180928_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformtemplate',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
