# Generated by Django 2.0.8 on 2018-09-13 04:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cp_comment', '0003_auto_20180913_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 9, 13, 4, 35, 56, 907074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 9, 13, 4, 35, 56, 907726, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='created_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 9, 13, 4, 35, 56, 906542, tzinfo=utc)),
        ),
    ]
