# Generated by Django 2.0.8 on 2018-09-13 04:41

import company_profile.cp_comment.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cp_comment', '0005_auto_20180913_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(db_index=True, default=company_profile.cp_comment.models.default_now),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 9, 13, 4, 41, 43, 885211, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='created_date',
            field=models.DateTimeField(db_index=True, default=company_profile.cp_comment.models.default_now),
        ),
    ]
