# Generated by Django 2.0.8 on 2018-09-22 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('cp_comment', '0007_auto_20180913_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_site', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitor_site', to='sites.Site'),
        ),
    ]
