# Generated by Django 2.0.8 on 2018-09-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_comment', '0008_auto_20180922_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
