# Generated by Django 2.0.8 on 2018-09-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_comment', '0009_auto_20180922_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(max_length=550, null=True),
        ),
    ]
