# Generated by Django 2.1 on 2018-08-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20180810_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='package_group',
        ),
        migrations.AddField(
            model_name='member',
            name='package_group',
            field=models.ManyToManyField(null=True, related_name='package_group', to='membership.PackageGroup'),
        ),
    ]
