# Generated by Django 2.1 on 2018-08-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20180810_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='package_group',
            field=models.ManyToManyField(blank=True, related_name='package_group', to='membership.PackageGroup'),
        ),
    ]
