# Generated by Django 2.1 on 2018-08-10 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('membership', '0004_auto_20180810_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site'),
        ),
    ]
