# Generated by Django 2.0.8 on 2018-10-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_member_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sidomo_user_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
