# Generated by Django 2.0.8 on 2018-10-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_member_sidomo_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='android_activation_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='member',
            name='ios_activation_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
