# Generated by Django 2.0.8 on 2018-09-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='page_view',
            field=models.IntegerField(default=0),
        ),
    ]
