# Generated by Django 2.0.8 on 2018-09-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_articles', '0002_article_page_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_preview',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
