# Generated by Django 2.0.8 on 2018-08-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp_articles', '0002_auto_20180810_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='headline',
            new_name='title',
        ),
    ]
