# Generated by Django 2.0.8 on 2018-08-10 14:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_member_site'),
        ('cp_articles', '0003_auto_20180810_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_author', to='membership.Member', verbose_name='author'),
        ),
        migrations.AddField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='cp/user_uploads/featured_images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_owner', to='membership.Member', verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
