# Generated by Django 2.0.8 on 2018-09-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_articles', '0003_article_is_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='article_category', to='cp_articles.Category'),
        ),
    ]
