# Generated by Django 2.0.8 on 2018-08-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('cp_articles', '0004_auto_20180810_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sites',
        ),
        migrations.AddField(
            model_name='article',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
