# Generated by Django 2.0.8 on 2018-10-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_articles', '0004_auto_20180922_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='page_view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
