# Generated by Django 2.0.8 on 2018-08-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_articles', '0007_auto_20180811_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
