# Generated by Django 2.0.8 on 2018-08-14 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp_articles', '0012_auto_20180814_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_site', to='sites.Site'),
        ),
    ]
