# Generated by Django 2.0.8 on 2018-09-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_articles', '0014_auto_20180815_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lead_in',
            field=models.CharField(default='', max_length=600),
        ),
    ]
