# Generated by Django 2.0.8 on 2018-09-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_articles', '0015_article_lead_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='article_category', to='cp_articles.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='lead_in',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
    ]
