# Generated by Django 2.0.8 on 2018-09-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_articles', '0016_auto_20180908_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='lead_in',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
