# Generated by Django 2.0.8 on 2018-09-09 07:48

from django.db import migrations, models
import django.db.models.deletion
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ('cp_articles', '0018_auto_20180908_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cp_articles.Article')),
            ],
            bases=('cp_articles.article',),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
