# Generated by Django 2.0.8 on 2018-09-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_articles', '0019_auto_20180909_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='class_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
