# Generated by Django 2.1 on 2018-08-10 09:56

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('cp_user_configs', '0001_initial'),
        ('cp_configs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandAssets',
            new_name='BrandAsset',
        ),
        migrations.RenameModel(
            old_name='Templates',
            new_name='Template',
        ),
        migrations.AlterModelOptions(
            name='brandasset',
            options={'verbose_name_plural': 'BrandAssets'},
        ),
        migrations.AlterModelOptions(
            name='brandidentity',
            options={'verbose_name_plural': 'BrandIdentities'},
        ),
        migrations.AlterModelOptions(
            name='colorscheme',
            options={'verbose_name_plural': 'ColorSchemes'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name_plural': 'Templates'},
        ),
    ]
