# Generated by Django 2.0.8 on 2018-08-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_configs', '0004_brandasset_main_photo_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandasset',
            name='main_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='cp/main_photo_2'),
        ),
    ]
