# Generated by Django 2.0.8 on 2018-08-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_configs', '0005_brandasset_main_photo_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandasset',
            name='extra_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='cp/extra_image'),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='extra_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='cp/extra_image'),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='extra_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='cp/extra_image'),
        ),
    ]
