# Generated by Django 2.0.8 on 2018-09-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_configs', '0006_auto_20180810_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='sample_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='cp/sample_image'),
        ),
        migrations.AddField(
            model_name='template',
            name='sample_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='cp/sample_image'),
        ),
        migrations.AddField(
            model_name='template',
            name='sample_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='cp/sample_image'),
        ),
    ]
