# Generated by Django 2.0.8 on 2018-10-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_configs', '0007_auto_20180927_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandasset',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
