# Generated by Django 2.0.8 on 2018-10-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_configs', '0008_auto_20181011_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='accent_light_color',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='light_color',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
