# Generated by Django 2.0.8 on 2018-10-17 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('st_database_wilayah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('alamat', models.CharField(blank=True, max_length=400, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('kecamatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='st_database_wilayah.Kecamatan')),
                ('kelurahan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='st_database_wilayah.Kelurahan')),
                ('kota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='st_database_wilayah.Kota')),
                ('provinsi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='st_database_wilayah.Provinsi')),
            ],
        ),
    ]
