# Generated by Django 2.0.8 on 2018-10-17 03:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0009_auto_20181011_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Nomor Telepon Harus memiliki format +62819999999 atau 0819999999'. Maksimal 15 Digit.", regex='^\\+?62?\\d{9,15}$')])),
                ('home_provinsi', models.CharField(blank=True, max_length=250)),
                ('home_kota', models.CharField(blank=True, max_length=250)),
                ('home_kecamatan', models.CharField(blank=True, max_length=250)),
                ('home_kelurahan', models.CharField(blank=True, max_length=250)),
                ('home_address', models.CharField(blank=True, max_length=250)),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile_photo')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_customer', to='membership.Member')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
