# Generated by Django 2.0.8 on 2018-10-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_shopping_cart', '0002_auto_20181019_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
