# Generated by Django 2.0.8 on 2018-08-10 15:48

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0005_member_site'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('published_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('banner_image_1', models.ImageField(blank=True, null=True, upload_to='cp/user_uploads/banner_images/')),
                ('banner_image_2', models.ImageField(blank=True, null=True, upload_to='cp/user_uploads/banner_images/')),
                ('banner_image_3', models.ImageField(blank=True, null=True, upload_to='cp/user_uploads/banner_images/')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_owner', to='membership.Member', verbose_name='owner')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
    ]
