# Generated by Django 2.0.8 on 2018-08-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
