# Generated by Django 2.0.8 on 2018-08-11 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp_pages', '0002_pagemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodel',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_page', to='sites.Site'),
        ),
    ]
