# Generated by Django 2.0.8 on 2018-08-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp_pages', '0003_auto_20180811_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagemodel',
            old_name='is_featured',
            new_name='is_published',
        ),
        migrations.RemoveField(
            model_name='pagemodel',
            name='published_date',
        ),
    ]
