# Generated by Django 2.0.8 on 2018-09-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_pages', '0006_auto_20180918_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='is_preview',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
