# Generated by Django 2.0.8 on 2018-10-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_catalog', '0003_category_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='Harga Produk', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_weight',
            field=models.PositiveIntegerField(help_text='Berat Satuan Produk dalam gram', null=True),
        ),
    ]
