# Generated by Django 2.0.8 on 2018-10-17 03:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0009_auto_20181011_0825'),
        ('st_customer', '0001_initial'),
        ('st_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(help_text='Total Belanja', null=True)),
                ('discount', models.IntegerField(help_text='Diskon Member', null=True)),
                ('shipping_cost', models.IntegerField(help_text='Ongkos Kirim', null=True)),
                ('total_payment', models.IntegerField(help_text='Total Belanja', null=True)),
                ('created_date', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('payment_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_valid', models.BooleanField(db_index=True, default=True)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('is_checked_out', models.BooleanField(db_index=True, default=False)),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('alamat_tujuan', models.CharField(blank=True, max_length=500)),
                ('service', models.CharField(blank=True, max_length=200)),
                ('sub_service', models.CharField(blank=True, max_length=200)),
                ('costumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='st_customer.Customer')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.Member')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PurchaseOrder',
                'verbose_name_plural': 'Purchase Orders',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('is_valid', models.BooleanField(db_index=True, default=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_in_order', to='st_catalog.Product')),
                ('product_referal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_order_referal', to='membership.Member')),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_in_order', to='st_purchase_order.PurchaseOrder')),
            ],
            options={
                'verbose_name_plural': 'items in Order',
            },
        ),
    ]
