# Generated by Django 2.0.8 on 2018-10-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st_purchase_order', '0002_purchaseorder_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='costumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_customer', to='st_customer.Customer'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_seller', to='membership.Member'),
        ),
    ]
